# Site settings
# These are used to personalize your new site.
title: Chamberlain L. Gibson 
logo: "images/chambs_pic.JPG"
description: 
  CSCI 496: Senior Portfolio<br />
  In partial fulfillment of the requirements for the degree of
  Bachelor of Science in Cyber Security
  <br/><br/>
  <a href="https://app.joinhandshake.com/stu/users/25818151">View My Resume</a>
  <br/><br/>
  <a href="https://www.linkedin.com/in/example/">View My LinkedIn Profile</a>
repository: "chamberlain-gibson/chamberlain-gibson.github.io"
github_username:  chamberlain-gibson 
google_analytics: UA-000000-0 

# Build setting
theme: jekyll-theme-minimal

