# Site settings
# These are used to personalize your new site.
title: Chamberlain Gibosn # your name here
logo: "/images/Handshake Profile Pic.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br /> elements if you don't need line breaks)
  CSCI 496: Senior Portfolio<br />
  In partial fulfillment of the requirements for the degree of
  Bachelor of Science in Cyber Security (class of 2023)
  <br /><br />
  <a href="https://app.joinhandshake.com/stu/users/25818151">View My Resume</a>
  <br /><br />
  <a href="https://www.linkedin.com/in/example/">View My LinkedIn Profile</a>
repository: "chamberlain-gibson/chamberlain-gibson.github.io"
github_username:  chamberlain-gibson # update with your username
google_analytics: UA-000000-0 # your Google Analytics tracking ID here

# Build setting
theme: jekyll-theme-minimal

